
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AGUSTICIDAD ASSIGN COMILLA CONTENIDO DESIGUAL DIV DOBLEIGUAL ENTERO GREATER ID ID IGUALMA IGUALMENO INCREMENT LBRACE LPAREN MAS MENOR MENOS MULTI NOVASIR NUMBER PAN PARAQOQUE PUNTCOM RBRACE RPAREN SEMI SIONO STRING UBUBUE VASIR VUELAOQUEinit : inicio\n            | opcion2\n            | opcion3\n            | opcion4inicio : PARAQOQUE LPAREN variable ID ASSIGN NUMBER PUNTCOM ID operador NUMBER PUNTCOM ID INCREMENT PUNTCOM RPAREN LBRACE  cualquier RBRACE\n              | PARAQOQUE LPAREN variable ID PUNTCOM ID operador NUMBER PUNTCOM ID INCREMENT PUNTCOM RPAREN LBRACE  cualquier RBRACEopcion2 : AGUSTICIDAD variable ID ASSIGN ident\n               | AGUSTICIDAD variable IDopcion3 : VASIR LPAREN ID operador ident RPAREN LBRACE cualquier RBRACE NOVASIR LBRACE cualquier RBRACEopcion4 : VUELAOQUE SIONO LPAREN  RPAREN LBRACE cualquier RBRACE\n               | VUELAOQUE ID LPAREN variable ID RPAREN LBRACE cualquier RBRACEcualquier : opcion2\n                | opcion4\n                | ident\n                | CONTENIDOvariable : UBUBUE\n                | PANoperador : GREATER\n                | IGUALMA\n                | IGUALMENO\n                | DOBLEIGUAL\n                | MENOR\n                | DESIGUAL\n                | ASSIGNident : ID  \n             | NUMBER'
    
_lr_action_items = {'PARAQOQUE':([0,],[6,]),'AGUSTICIDAD':([0,40,53,55,69,77,80,],[7,7,7,7,7,7,7,]),'VASIR':([0,],[8,]),'VUELAOQUE':([0,40,53,55,69,77,80,],[9,9,9,9,9,9,9,]),'$end':([1,2,3,4,5,18,36,37,38,54,63,75,81,83,],[0,-1,-2,-3,-4,-8,-25,-7,-26,-10,-11,-9,-6,-5,]),'LPAREN':([6,8,15,16,],[10,14,20,21,]),'UBUBUE':([7,10,21,],[12,12,12,]),'PAN':([7,10,21,],[13,13,13,]),'SIONO':([9,],[15,]),'ID':([9,11,12,13,14,17,23,24,25,26,27,28,29,30,31,33,35,40,51,53,55,61,67,69,77,80,],[16,18,-16,-17,19,22,36,36,-18,-19,-20,-21,-22,-23,-24,41,43,36,56,36,36,65,70,36,36,36,]),'ASSIGN':([18,19,22,43,56,],[23,31,34,31,31,]),'RBRACE':([18,36,37,38,45,46,47,48,49,54,58,59,63,72,79,82,],[-8,-25,-7,-26,54,-12,-13,-14,-15,-10,62,63,-11,75,81,83,]),'GREATER':([19,43,56,],[25,25,25,]),'IGUALMA':([19,43,56,],[26,26,26,]),'IGUALMENO':([19,43,56,],[27,27,27,]),'DOBLEIGUAL':([19,43,56,],[28,28,28,]),'MENOR':([19,43,56,],[29,29,29,]),'DESIGUAL':([19,43,56,],[30,30,30,]),'RPAREN':([20,36,38,39,41,71,76,],[32,-25,-26,44,50,74,78,]),'PUNTCOM':([22,42,57,64,68,73,],[35,51,61,67,71,76,]),'NUMBER':([23,24,25,26,27,28,29,30,31,34,40,52,53,55,60,69,77,80,],[38,38,-18,-19,-20,-21,-22,-23,-24,42,38,57,38,38,64,38,38,38,]),'LBRACE':([32,44,50,66,74,78,],[40,53,55,69,77,80,]),'CONTENIDO':([40,53,55,69,77,80,],[49,49,49,49,49,49,]),'NOVASIR':([62,],[66,]),'INCREMENT':([65,70,],[68,73,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'inicio':([0,],[2,]),'opcion2':([0,40,53,55,69,77,80,],[3,46,46,46,46,46,46,]),'opcion3':([0,],[4,]),'opcion4':([0,40,53,55,69,77,80,],[5,47,47,47,47,47,47,]),'variable':([7,10,21,],[11,17,33,]),'operador':([19,43,56,],[24,52,60,]),'ident':([23,24,40,53,55,69,77,80,],[37,39,48,48,48,48,48,48,]),'cualquier':([40,53,55,69,77,80,],[45,58,59,72,79,82,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> inicio','init',1,'p_init','analizador_sintactico.py',9),
  ('init -> opcion2','init',1,'p_init','analizador_sintactico.py',10),
  ('init -> opcion3','init',1,'p_init','analizador_sintactico.py',11),
  ('init -> opcion4','init',1,'p_init','analizador_sintactico.py',12),
  ('inicio -> PARAQOQUE LPAREN variable ID ASSIGN NUMBER PUNTCOM ID operador NUMBER PUNTCOM ID INCREMENT PUNTCOM RPAREN LBRACE cualquier RBRACE','inicio',18,'p_inicio','analizador_sintactico.py',15),
  ('inicio -> PARAQOQUE LPAREN variable ID PUNTCOM ID operador NUMBER PUNTCOM ID INCREMENT PUNTCOM RPAREN LBRACE cualquier RBRACE','inicio',16,'p_inicio','analizador_sintactico.py',16),
  ('opcion2 -> AGUSTICIDAD variable ID ASSIGN ident','opcion2',5,'p_opcion2','analizador_sintactico.py',19),
  ('opcion2 -> AGUSTICIDAD variable ID','opcion2',3,'p_opcion2','analizador_sintactico.py',20),
  ('opcion3 -> VASIR LPAREN ID operador ident RPAREN LBRACE cualquier RBRACE NOVASIR LBRACE cualquier RBRACE','opcion3',13,'p_opcion3','analizador_sintactico.py',23),
  ('opcion4 -> VUELAOQUE SIONO LPAREN RPAREN LBRACE cualquier RBRACE','opcion4',7,'p_opcion4','analizador_sintactico.py',26),
  ('opcion4 -> VUELAOQUE ID LPAREN variable ID RPAREN LBRACE cualquier RBRACE','opcion4',9,'p_opcion4','analizador_sintactico.py',27),
  ('cualquier -> opcion2','cualquier',1,'p_cualquier','analizador_sintactico.py',29),
  ('cualquier -> opcion4','cualquier',1,'p_cualquier','analizador_sintactico.py',30),
  ('cualquier -> ident','cualquier',1,'p_cualquier','analizador_sintactico.py',31),
  ('cualquier -> CONTENIDO','cualquier',1,'p_cualquier','analizador_sintactico.py',32),
  ('variable -> UBUBUE','variable',1,'p_variable','analizador_sintactico.py',34),
  ('variable -> PAN','variable',1,'p_variable','analizador_sintactico.py',35),
  ('operador -> GREATER','operador',1,'p_operador','analizador_sintactico.py',38),
  ('operador -> IGUALMA','operador',1,'p_operador','analizador_sintactico.py',39),
  ('operador -> IGUALMENO','operador',1,'p_operador','analizador_sintactico.py',40),
  ('operador -> DOBLEIGUAL','operador',1,'p_operador','analizador_sintactico.py',41),
  ('operador -> MENOR','operador',1,'p_operador','analizador_sintactico.py',42),
  ('operador -> DESIGUAL','operador',1,'p_operador','analizador_sintactico.py',43),
  ('operador -> ASSIGN','operador',1,'p_operador','analizador_sintactico.py',44),
  ('ident -> ID','ident',1,'p_ident','analizador_sintactico.py',46),
  ('ident -> NUMBER','ident',1,'p_ident','analizador_sintactico.py',47),
]
